name: IPTV Argentina Auto

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          playwright install
          playwright install chromium
          playwright install-deps

      - name: Ejecutar script
        run: python cazador.py || true

      - name: Guardar lista
        run: |
          git config --global user.name "Daniel-Bot"
          git config --global user.email "bot@github.com"
          git add lista_fresca.m3u
          git diff --cached --quiet || git commit -m "Update lista IPTV"
          git push
